#install.packages("Seurat")
library(Seurat)
library(patchwork)
library(ggplot2)
library(gplots)
library(cowplot)
library(devtools)
library(plyr)
library(matrixStats)
library("ggplot2")
library("reshape2")
library(magrittr)
library(dplyr)    
library(readr)
#library("readxl")
library(UpSetR)
library(tidyverse)
library(grid)
library(crone)
library(ggvenn)
setwd("/Users/maewoodsphd/mVSTManuscript/Rscripts")

#' @include generics.R
#'
NULL

#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
# Functions
#%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
#' Combine single cell data and annotate with cell labels based on functionality
#'
#' This function will combine multiple Seurat objects and assign labels based on 
#' additional tables stored in csv formt, we construct the positive definite covariance matrix
#' of the reference data set Signature.ref. Takes as input two Seurat objects, one containing
#' the query cells and another containing the reference. A gene list 
#' used to constuct the distance and output path for plotting. Other parameters are listed for debugging, 
#' but can be left
#' as default values.
#'
#' @param cell.array A Seurat object containing cells that are to be assigned a distance
#' @param summary.df A data frame containing a list of TCR sequences, the frequency 
#' of cells expressing those sequences in the CD4 and CD8 population and total number of cells 
#' @param path.glist Directory containing gene set
#' @param path.outs Directory of cell type labels stored in csv format
#' @param signature.ref A Seurat object containing the distribution used to generate mahalanobis distance
#' @param scramble Print maximum distance for dataset
#' neighbors. FALSE by default
#' @param which.gene Sets the gene used for ploting
#' @param specificity.quartile A \code{\link{ModalityWeights}} object generated by
#' \code{FindModalityWeights}
#' @param verbose Print progress bars and output
#'
#' @return A Seurat object containing metadata with mahalanobis distances.
#' @concept annotation
#' @export
#'

###################################################
####Unstimulated ##################################
###################################################

markerGene=c("IFNG","CRTAM","CD69","TNF","CD70","TNFRSF9")
mask=c("TRBV.","TRAV.")

index.control=1
sample.name = c("UMO","CMV","EBV","BKV")
gex.path=list("../outs_t1/UMO","../outs_t1/CMV","../outs_t1/EBV","../outs_t1/BKV")
vdj.path=list("../vdj_t1/UMO/all_contig_annotations.csv",
              "../vdj_t1/CMV/all_contig_annotations.csv",
              "../vdj_t1/EBV/all_contig_annotations.csv",
              "../vdj_t1/BKV/all_contig_annotations.csv")
save_dir="../RDS/ThreeHourStim.rds"


ThreeHourStim=CombineData(dir_rna1,dir_rna2,dir_rna3,dir_rna4,
dir_vdj1,dir_vdj2,dir_vdj3,dir_vdj4,markerGene,mask,save_dir)

save_dir="../RDS/SixHourStim.rds"

gex.path=list("../outs_t2/CMV","../outs_t2/EBV","../outs_t2/BKV","../outs_t2/UMO")
vdj.path=list("../vdj_t2/UMO/all_contig_annotations.csv",
              "../vdj_t2/CMV/all_contig_annotations.csv",
              "../vdj_t2/EBV/all_contig_annotations.csv",
              "../vdj_t2/BKV/all_contig_annotations.csv")
save_dir="../RDS/SixHourStim.rds"



SixHourStim=CombineData(dir_rna1,dir_rna2,dir_rna3,dir_rna4,
                          dir_vdj1,dir_vdj2,dir_vdj3,dir_vdj4,markerGene,mask,save_dir)

CombineData <- function(
  gex.path,
  vdj.path,
  markerGene,
  mask,save_dir
){
  
Clonal_Obs= vector(mode = "list", length = length(gex.path))
VDJ_Obs= vector(mode = "list", length = length(vdj.path))
tcrhash= vector(mode = "list", length = length(vdj.path))
  
for(k in 1:length(gex.path)){
  print(paste(paste("Reading in gene expression for sample ",k,sep=""),"...",sep=""))
clonal.data <- Read10X(data.dir = gex.path[[k]])
Clonal_Obs[[k]] <- CreateSeuratObject(counts = clonal.data,project = sample.name[k])
Clonal_Obs[[k]][["percent.mt"]] <- PercentageFeatureSet(Clonal_Obs[[k]], pattern = "^MT-")
Clonal_Obs[[k]]<- subset(Clonal_Obs[[k]], subset = nFeature_RNA > 100 & nFeature_RNA < 10000 & percent.mt < 5)
RnaStoreUMO=Clonal_Obs[[k]]@assays$RNA@counts

#VDJ list with barcodes
print(paste(paste("Reading in VDJ for sample ",k,sep=""),"...",sep=""))
VDJ_Obs[[k]] <- read.csv(vdj.path[[k]])
tcrUMO_cell=subset(VDJ_Obs[[k]],productive=="true" & is_cell=="true")
TCRlistUMO=tcrUMO_cell$barcode
joint.bcsUMO <- intersect(colnames(RnaStoreUMO), TCRlistUMO)
#Remove barcodes from list that don't match VDJ
tcrhash[[k]]=subset(VDJ_Obs[[k]],VDJ_Obs[[k]]$barcode %in% joint.bcsUMO)
mvsts.UMO <- RnaStoreUMO[, joint.bcsUMO]
Clonal_Obs[[k]]=Clonal_Obs[[k]][,joint.bcsUMO]

###remove genes that are not of interest
for(c in 1:length(mask)){
Allgenes=row.names(Clonal_Obs[[k]])
Gset=Allgenes[grep(mask[c],Allgenes)]
NewGeneSet=setdiff(Allgenes,Gset)
IndexesGTR=match(NewGeneSet,row.names(Clonal_Obs[[k]]))
Clonal_Obs[[k]] <- Clonal_Obs[[k]][IndexesGTR,]
}

####Genes of interest
Gene_indUMO=match(markerGene,row.names(mvsts.UMO))
CD8_UMO=match("CD8A",row.names(mvsts.UMO))
CD4_UMO=match("CD4",row.names(mvsts.UMO))
CD8cells=rep(0,length(mvsts.UMO[Gene_indUMO[1],]))
CD4cells=rep(0,length(mvsts.UMO[Gene_indUMO[1],]))

vec1=mvsts.UMO[CD4_UMO,]
vec2=mvsts.UMO[CD8_UMO,]

for(g in 1:length(CD8cells)){
  if((vec2[g]==0)&(vec1[g]>0)){
    CD4cells[g]=1
  }
  else if((vec2[g]>0)&(vec1[g]==0)){
    CD8cells[g]=1
  }
  else{}
}
rm(vec1)
rm(vec2)

Clonal_Obs[[k]]=AddMetaData(Clonal_Obs[[k]], CD8cells, col.name = 'CD8cells')
Clonal_Obs[[k]]=AddMetaData(Clonal_Obs[[k]], CD4cells, col.name = 'CD4cells')

rm(CD8cells)
rm(CD4cells)
#Check for errors
plot(log10(mvsts.UMO[Gene_indUMO[3],]),log10(mvsts.UMO[Gene_indUMO[2],]),xlab=paste(Gene_indUMO[3]," (log10 UMIs)",sep=""),ylab=paste(Gene_indUMO[2]," (log10 UMIs)",sep=""),col=rgb(red=0, green = 0, blue = 0, alpha=0.5),pch=16,cex=1,xlim=c(0,4.5),ylim=c(0,4.5))
plot(log10(mvsts.UMO[CD8_UMO,]),log10(mvsts.UMO[CD4_UMO,]),xlab="CD8",ylab="CD4",col=rgb(red=0, green = 0, blue = 0, alpha=0.5),pch=16,cex=1,xlim=c(0,4.5),ylim=c(0,4.5))
print(paste(paste("Starting scTRansform sample ",k,sep=""),"...",sep=""))
Clonal_Obs[[k]] <- SCTransform(Clonal_Obs[[k]], vars.to.regress = "percent.mt", verbose = FALSE,variable.features.n = 7000)
Gene_indUMO=match(markerGene,row.names(Clonal_Obs[[k]]))
d1=as.matrix(Clonal_Obs[[k]][["SCT"]]@data)[Gene_indUMO,]
alist <- 1:length(Gene_indUMO)
if(k==index.control){
cutoff=lapply(alist, function(alist) quantile(d1[alist,],.975)[[1]])
}

Thresholds=matrix("unassigned",nrow=dim(Clonal_Obs[[k]])[2],ncol=length(Gene_indUMO))
for(s in 1:length(Gene_indUMO)){
  vec1=Clonal_Obs[[k]][Gene_indUMO[s],][["SCT"]]@data
for(j in 1:dim(Clonal_Obs[[k]])[2]){
  if(vec1[j]>cutoff[s]){
    Thresholds[j,s]="high"
  }
}
  Clonal_Obs[[k]]=AddMetaData(Clonal_Obs[[k]], Thresholds[,s], col.name = paste("Threshold_",markerGene[s],sep=""))
}

rm(mvsts.UMO)
rm(RnaStoreUMO)
rm(clonal.data)

}

#####################################################
##         Generate clonotypes by TCRB (na)        ##
#####################################################
mono= vector(mode = "list", length = length(vdj.path))
monoTRBNA=vector(mode = "list", length = length(vdj.path))
monoTRBAA=vector(mode = "list", length = length(vdj.path))
monoclono=vector(mode = "list", length = length(vdj.path))

for(k in 1:length(vdj.path)){
mono[[k]]=rep(0,dim(Clonal_Obs[[k]])[2])
monoTRBNA[[k]]=rep("unassigned",dim(Clonal_Obs[[k]])[2])
monoTRBAA[[k]]=rep("unassigned",dim(Clonal_Obs[[k]])[2])
monoclono[[k]]=rep("unassigned",dim(Clonal_Obs[[k]])[2])

##TRB loop for each single cell
for(j in 1:dim(Clonal_Obs[[k]])[2]){
  
  monoB[j]=colnames(Clonal_Obs[[k]])[j]
  set_umo=subset(tcrhash[[k]],barcode==colnames(Clonal_Obs[[k]])[j] & productive=="true" & chain=="TRB")
  TCRs=set_umo
  len=length(set_umo$reads)
  if(len==0){
    
  }
  else if(len==1){
    monoTRBNA[j]=set_umo$cdr3_nt
    monoTRBAA[j]=set_umo$cdr3
  }
  else{
    position= which.max(set_umo$reads)
    monoTRBNA[j]=set_umo$cdr3_nt[position]
    monoTRBAA[j]=set_umo$cdr3[position]
  }
  
}

}

IntersectTCRs=monoTRBNA[1]
for(h in 2:length(gex.path)){
  IntersectTCRs = intersect(IntersectTCRs,monoTRBNA[h])
}

Tailmono=setdiff(monoTRBNA[[1]],IntersectTCRs)
IMTCRs=c(IntersectTCRs,Tailmono)
for(h in 2:length(gex.path)){
Tailmono=setdiff(monoTRBNA[[h]],IMTCRs)
IMTCRs=c(IntersectTCRs,Tailmono)
}

SizesC_Obj= vector(mode = "list", length = length(gex.path))
for(q in 1:length(gex.path)){
  SizesC_Obj[q]= rep(0,length(IMTCRs))
  for(j in 1:length(IMTCRs)){
    SizesC_Obj[q][j]=length(subset(tcrhash[q],cdr3_nt==IMTCRs[j] & productive=="true" & chain=="TRB")$barcode)
  }
  
}


Nclono= vector(mode = "list", length = length(gex.path))
for(q in 1:length(gex.path)){
  OSM=order(SizesC_Obj[q],decreasing=TRUE)
  Nclono[q]=rep("blank",length(IMTCRs))
for(f in 1: length(IMTCRs)){
  if(OSM[f]==7){
    
  }
  else{
    Nclono[q][OSM[f]]=paste("clonotype",f,sep="")
  }
}
}
clonotypes.nucleic.acid=data.frame(TCRs=IMTCRs,clonoT=Nclono,freqT=SizesMono)

all.Cname= vector(mode = "list", length = length(gex.path))
  
all.Size= vector(mode = "list", length = length(gex.path))
for(q in 1:length(gex.path))
{
  all.Cname[q]=rep("unassigned",dim(Clonal_Obs[[k]])[2])
  all.Size[q]=rep(0,dim(Clonal_Obs[[k]])[2])
}

##TRB loop
for(j in 1:dim(Clonal_Obs[[k]])[2]){
  
  if(monoTRBNA[k][j]=="unassigned"){
    
  }
  else{
    all.Size[k][j]=subset(clonotypes.nucleic.acid,TCRs==monoTRBNA[k][j])$freqT
    all.Cname[k][j]=subset(clonotypes.nucleic.acid,TCRs==monoTRBNA[k][j])$clonoT
  }
  
}

Clonal_Obs[[k]]=AddMetaData(Clonal_Obs[[k]], Cname, col.name = 'clonotype')
Clonal_Obs[[k]]=AddMetaData(Clonal_Obs[[k]], Size, col.name = 'countcln')


#####################################################
# Now add clonotype # and size to metadata vectors ##
#####################################################

clono.nucleotide.seq=rep("unassigned",dim(Clonal_Obs[[k]])[2])
clono.aminoacid.seq=rep("unassigned",dim(Clonal_Obs[[k]])[2])

##TRB loop
for(j in 1:dim(Clonal_Obs[[k]])[2]){
  
  monoB[j]=colnames(Clonal_Obs[[k]])[j]
  set_umo=subset(tcrhash[[k]],barcode==colnames(Clonal_Obs[[k]])[j] & productive=="true" & chain=="TRB")
  TCRs=set_umo
  len=length(set_umo$reads)
  if(len==0){
    
  }
  else if(len==1){
    mTRBNA=set_umo$cdr3_nt
    mTRBAA=set_umo$cdr3
    clono.nucleotide.seq[j]=mTRBNA
    clono.aminoacid.seq[j]=mTRBAA
  }
  else{
    position= which.max(set_umo$reads)
    mTRBNA=set_umo$cdr3_nt[position]
    mTRBAA=set_umo$cdr3[position]
    clono.nucleotide.seq[j]=mTRBNA
    clono.aminoacid.seq[j]=mTRBAA
  }
  
}

Clonal_Obs[[k]]=AddMetaData(Clonal_Obs[[k]], clono.nucleotide.seq, col.name = 'cdr3_na')
Clonal_Obs[[k]]=AddMetaData(Clonal_Obs[[k]], clono.aminoacid.seq, col.name = 'cdr3')

Dataset=Clonal_Obs
saveRDS(Dataset,save_dir)
return(Dataset)
}